name = "discord-worker"
main = "./src/server.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date="2025-05-05"

[triggers]
crons = ["0 17 * * *"]

[observability.logs]
enabled = true

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
# VOICE_CHANNEL_ID